GET http://localhost:3001/cards

###
GET http://localhost:3001/cards/6117fc3a3d2bda2e880b14ce

###
DELETE http://localhost:3001/cards/6118e33de5bad0178084b37e

### 
POST http://localhost:3001/cards
Content-Type: application/json

{
    "word": "test",
    "transcription": "[test]",
    "translation": "тест",
    "learned": true,
    "examples": ["пример пример пример", "example example example"],
    "colection": ["11111111111","2222222222222222"],
     "repetitions": [{
       "isItRight": true,
      "data": "d33ew" 
    }],
    "img": "https://image.shutterstock.com/image-vector/design-concept-word-english-website-260nw-1043962963.jpg"
}
